FROM nginx:latest
RUN echo '<h1>Hello World ! </h1>' > /usr/share/nginx/html/index.html

# rodar o terminal dentro dessa pasta
# docker image build -t ex-simple-build . 
# colocar para funcionar
# docker container run -p 80:80 ex-simple-build
# so acessar o browser na localhost:80 e pronto la vai esta funcionando